// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package router

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TestingParameter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey           string   `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,6,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestingParameter) Reset()         { *m = TestingParameter{} }
func (m *TestingParameter) String() string { return proto.CompactTextString(m) }
func (*TestingParameter) ProtoMessage()    {}
func (*TestingParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *TestingParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestingParameter.Unmarshal(m, b)
}
func (m *TestingParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestingParameter.Marshal(b, m, deterministic)
}
func (m *TestingParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestingParameter.Merge(m, src)
}
func (m *TestingParameter) XXX_Size() int {
	return xxx_messageInfo_TestingParameter.Size(m)
}
func (m *TestingParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_TestingParameter.DiscardUnknown(m)
}

var xxx_messageInfo_TestingParameter proto.InternalMessageInfo

func (m *TestingParameter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TestingParameter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *TestingParameter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TestingParameter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TestingParameter) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *TestingParameter) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type PutParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey           string   `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,7,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutParameter) Reset()         { *m = PutParameter{} }
func (m *PutParameter) String() string { return proto.CompactTextString(m) }
func (*PutParameter) ProtoMessage()    {}
func (*PutParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *PutParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutParameter.Unmarshal(m, b)
}
func (m *PutParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutParameter.Marshal(b, m, deterministic)
}
func (m *PutParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutParameter.Merge(m, src)
}
func (m *PutParameter) XXX_Size() int {
	return xxx_messageInfo_PutParameter.Size(m)
}
func (m *PutParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_PutParameter.DiscardUnknown(m)
}

var xxx_messageInfo_PutParameter proto.InternalMessageInfo

func (m *PutParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PutParameter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PutParameter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PutParameter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PutParameter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PutParameter) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *PutParameter) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type ExecParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Bash                 string   `protobuf:"bytes,2,opt,name=bash,proto3" json:"bash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecParameter) Reset()         { *m = ExecParameter{} }
func (m *ExecParameter) String() string { return proto.CompactTextString(m) }
func (*ExecParameter) ProtoMessage()    {}
func (*ExecParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *ExecParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecParameter.Unmarshal(m, b)
}
func (m *ExecParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecParameter.Marshal(b, m, deterministic)
}
func (m *ExecParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecParameter.Merge(m, src)
}
func (m *ExecParameter) XXX_Size() int {
	return xxx_messageInfo_ExecParameter.Size(m)
}
func (m *ExecParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecParameter.DiscardUnknown(m)
}

var xxx_messageInfo_ExecParameter proto.InternalMessageInfo

func (m *ExecParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ExecParameter) GetBash() string {
	if m != nil {
		return m.Bash
	}
	return ""
}

type ExecResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *ExecResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DeleteParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParameter) Reset()         { *m = DeleteParameter{} }
func (m *DeleteParameter) String() string { return proto.CompactTextString(m) }
func (*DeleteParameter) ProtoMessage()    {}
func (*DeleteParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{5}
}

func (m *DeleteParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParameter.Unmarshal(m, b)
}
func (m *DeleteParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParameter.Marshal(b, m, deterministic)
}
func (m *DeleteParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParameter.Merge(m, src)
}
func (m *DeleteParameter) XXX_Size() int {
	return xxx_messageInfo_DeleteParameter.Size(m)
}
func (m *DeleteParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParameter.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParameter proto.InternalMessageInfo

func (m *DeleteParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type GetParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParameter) Reset()         { *m = GetParameter{} }
func (m *GetParameter) String() string { return proto.CompactTextString(m) }
func (*GetParameter) ProtoMessage()    {}
func (*GetParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{6}
}

func (m *GetParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParameter.Unmarshal(m, b)
}
func (m *GetParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParameter.Marshal(b, m, deterministic)
}
func (m *GetParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParameter.Merge(m, src)
}
func (m *GetParameter) XXX_Size() int {
	return xxx_messageInfo_GetParameter.Size(m)
}
func (m *GetParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GetParameter proto.InternalMessageInfo

func (m *GetParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type GetResponse struct {
	Error                uint32       `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *Information `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *GetResponse) GetData() *Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type Information struct {
	Identity             string          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Host                 string          `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32          `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string          `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Connected            string          `protobuf:"bytes,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Tunnels              []*TunnelOption `protobuf:"bytes,6,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Information) Reset()         { *m = Information{} }
func (m *Information) String() string { return proto.CompactTextString(m) }
func (*Information) ProtoMessage()    {}
func (*Information) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{8}
}

func (m *Information) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information.Unmarshal(m, b)
}
func (m *Information) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information.Marshal(b, m, deterministic)
}
func (m *Information) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information.Merge(m, src)
}
func (m *Information) XXX_Size() int {
	return xxx_messageInfo_Information.Size(m)
}
func (m *Information) XXX_DiscardUnknown() {
	xxx_messageInfo_Information.DiscardUnknown(m)
}

var xxx_messageInfo_Information proto.InternalMessageInfo

func (m *Information) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Information) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Information) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Information) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Information) GetConnected() string {
	if m != nil {
		return m.Connected
	}
	return ""
}

func (m *Information) GetTunnels() []*TunnelOption {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

type TunnelOption struct {
	SrcIp                string   `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort              uint32   `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp                string   `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort              uint32   `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelOption) Reset()         { *m = TunnelOption{} }
func (m *TunnelOption) String() string { return proto.CompactTextString(m) }
func (*TunnelOption) ProtoMessage()    {}
func (*TunnelOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{9}
}

func (m *TunnelOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelOption.Unmarshal(m, b)
}
func (m *TunnelOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelOption.Marshal(b, m, deterministic)
}
func (m *TunnelOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelOption.Merge(m, src)
}
func (m *TunnelOption) XXX_Size() int {
	return xxx_messageInfo_TunnelOption.Size(m)
}
func (m *TunnelOption) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelOption.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelOption proto.InternalMessageInfo

func (m *TunnelOption) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *TunnelOption) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *TunnelOption) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *TunnelOption) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

type AllParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllParameter) Reset()         { *m = AllParameter{} }
func (m *AllParameter) String() string { return proto.CompactTextString(m) }
func (*AllParameter) ProtoMessage()    {}
func (*AllParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{10}
}

func (m *AllParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllParameter.Unmarshal(m, b)
}
func (m *AllParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllParameter.Marshal(b, m, deterministic)
}
func (m *AllParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllParameter.Merge(m, src)
}
func (m *AllParameter) XXX_Size() int {
	return xxx_messageInfo_AllParameter.Size(m)
}
func (m *AllParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_AllParameter.DiscardUnknown(m)
}

var xxx_messageInfo_AllParameter proto.InternalMessageInfo

type AllResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllResponse) Reset()         { *m = AllResponse{} }
func (m *AllResponse) String() string { return proto.CompactTextString(m) }
func (*AllResponse) ProtoMessage()    {}
func (*AllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{11}
}

func (m *AllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllResponse.Unmarshal(m, b)
}
func (m *AllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllResponse.Marshal(b, m, deterministic)
}
func (m *AllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllResponse.Merge(m, src)
}
func (m *AllResponse) XXX_Size() int {
	return xxx_messageInfo_AllResponse.Size(m)
}
func (m *AllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllResponse proto.InternalMessageInfo

func (m *AllResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *AllResponse) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListsParameter struct {
	Identity             []string `protobuf:"bytes,1,rep,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListsParameter) Reset()         { *m = ListsParameter{} }
func (m *ListsParameter) String() string { return proto.CompactTextString(m) }
func (*ListsParameter) ProtoMessage()    {}
func (*ListsParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{12}
}

func (m *ListsParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsParameter.Unmarshal(m, b)
}
func (m *ListsParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsParameter.Marshal(b, m, deterministic)
}
func (m *ListsParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsParameter.Merge(m, src)
}
func (m *ListsParameter) XXX_Size() int {
	return xxx_messageInfo_ListsParameter.Size(m)
}
func (m *ListsParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsParameter.DiscardUnknown(m)
}

var xxx_messageInfo_ListsParameter proto.InternalMessageInfo

func (m *ListsParameter) GetIdentity() []string {
	if m != nil {
		return m.Identity
	}
	return nil
}

type ListsResponse struct {
	Error                uint32         `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*Information `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListsResponse) Reset()         { *m = ListsResponse{} }
func (m *ListsResponse) String() string { return proto.CompactTextString(m) }
func (*ListsResponse) ProtoMessage()    {}
func (*ListsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{13}
}

func (m *ListsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsResponse.Unmarshal(m, b)
}
func (m *ListsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsResponse.Marshal(b, m, deterministic)
}
func (m *ListsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsResponse.Merge(m, src)
}
func (m *ListsResponse) XXX_Size() int {
	return xxx_messageInfo_ListsResponse.Size(m)
}
func (m *ListsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListsResponse proto.InternalMessageInfo

func (m *ListsResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *ListsResponse) GetData() []*Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type TunnelsParameter struct {
	Identity             string          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Tunnels              []*TunnelOption `protobuf:"bytes,2,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TunnelsParameter) Reset()         { *m = TunnelsParameter{} }
func (m *TunnelsParameter) String() string { return proto.CompactTextString(m) }
func (*TunnelsParameter) ProtoMessage()    {}
func (*TunnelsParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{14}
}

func (m *TunnelsParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelsParameter.Unmarshal(m, b)
}
func (m *TunnelsParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelsParameter.Marshal(b, m, deterministic)
}
func (m *TunnelsParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelsParameter.Merge(m, src)
}
func (m *TunnelsParameter) XXX_Size() int {
	return xxx_messageInfo_TunnelsParameter.Size(m)
}
func (m *TunnelsParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelsParameter.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelsParameter proto.InternalMessageInfo

func (m *TunnelsParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *TunnelsParameter) GetTunnels() []*TunnelOption {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonResponse)(nil), "CommonResponse")
	proto.RegisterType((*TestingParameter)(nil), "TestingParameter")
	proto.RegisterType((*PutParameter)(nil), "PutParameter")
	proto.RegisterType((*ExecParameter)(nil), "ExecParameter")
	proto.RegisterType((*ExecResponse)(nil), "ExecResponse")
	proto.RegisterType((*DeleteParameter)(nil), "DeleteParameter")
	proto.RegisterType((*GetParameter)(nil), "GetParameter")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*Information)(nil), "Information")
	proto.RegisterType((*TunnelOption)(nil), "TunnelOption")
	proto.RegisterType((*AllParameter)(nil), "AllParameter")
	proto.RegisterType((*AllResponse)(nil), "AllResponse")
	proto.RegisterType((*ListsParameter)(nil), "ListsParameter")
	proto.RegisterType((*ListsResponse)(nil), "ListsResponse")
	proto.RegisterType((*TunnelsParameter)(nil), "TunnelsParameter")
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc) }

var fileDescriptor_367072455c71aedc = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x4e, 0xe2, 0xc4, 0x69, 0x27, 0x76, 0x1a, 0x56, 0x54, 0x32, 0x16, 0x82, 0x68, 0x85, 0xd4,
	0xaa, 0xa2, 0x8b, 0x54, 0x0e, 0xf4, 0x86, 0x2a, 0xa8, 0xa2, 0x0a, 0x24, 0x22, 0xab, 0x12, 0xc7,
	0xca, 0xb5, 0x87, 0xd6, 0xc2, 0xf6, 0x5a, 0xbb, 0x1b, 0xa0, 0xcf, 0x05, 0x6f, 0xc1, 0x63, 0xf0,
	0x22, 0x68, 0xd7, 0x8e, 0xeb, 0x94, 0xb4, 0xf1, 0x85, 0xdb, 0xfc, 0x3a, 0xdf, 0xcc, 0xb7, 0xdf,
	0x04, 0x1c, 0xc1, 0x17, 0x0a, 0x05, 0x2b, 0x04, 0x57, 0x9c, 0x1e, 0xc3, 0xf8, 0x1d, 0xcf, 0x32,
	0x9e, 0x07, 0x28, 0x0b, 0x9e, 0x4b, 0x24, 0x8f, 0x61, 0x80, 0x42, 0x70, 0xe1, 0x75, 0xa7, 0xdd,
	0x7d, 0x37, 0x28, 0x1d, 0x32, 0x01, 0x2b, 0x93, 0x57, 0x5e, 0x6f, 0xda, 0xdd, 0xdf, 0x0e, 0xb4,
	0x49, 0x7f, 0x76, 0x61, 0x72, 0x8e, 0x52, 0x25, 0xf9, 0xd5, 0x3c, 0x14, 0x61, 0x86, 0x0a, 0x05,
	0x21, 0xd0, 0xbf, 0xe6, 0x52, 0x99, 0xde, 0xed, 0xc0, 0xd8, 0x3a, 0x56, 0x70, 0xa1, 0x4c, 0xaf,
	0x1b, 0x18, 0x9b, 0xf8, 0xb0, 0xb5, 0x90, 0x28, 0xf2, 0x30, 0x43, 0xcf, 0x32, 0xb5, 0xb5, 0xaf,
	0x73, 0x45, 0x28, 0xe5, 0x77, 0x2e, 0x62, 0xaf, 0x5f, 0xe6, 0x96, 0x3e, 0x79, 0x0e, 0xa3, 0x42,
	0x24, 0xdf, 0x42, 0x85, 0x17, 0x5f, 0xf1, 0xc6, 0x1b, 0x98, 0x34, 0x54, 0xa1, 0x0f, 0x78, 0x43,
	0x9e, 0x01, 0xe8, 0xe2, 0xe2, 0x5a, 0x84, 0x12, 0x3d, 0xbb, 0xca, 0xd7, 0x11, 0xfa, 0xbb, 0x0b,
	0xce, 0x7c, 0xa1, 0x6e, 0x11, 0xfb, 0xb0, 0x95, 0xc4, 0x98, 0xab, 0x44, 0xdd, 0x54, 0xa8, 0x6b,
	0xbf, 0x9e, 0xa6, 0xb7, 0x66, 0x1a, 0xeb, 0x9e, 0x69, 0xfa, 0x0f, 0x4c, 0x33, 0x78, 0x78, 0x1a,
	0x7b, 0xc3, 0x34, 0xc3, 0x7f, 0xa6, 0x79, 0x0b, 0xee, 0xe9, 0x0f, 0x8c, 0x5a, 0x4f, 0x73, 0x19,
	0xca, 0xeb, 0xe5, 0x34, 0xda, 0xa6, 0xc7, 0xe0, 0xe8, 0x0f, 0x6c, 0x20, 0x9f, 0x40, 0x3f, 0x0e,
	0x55, 0xb8, 0xec, 0xd4, 0x36, 0x3d, 0x84, 0x9d, 0xf7, 0x98, 0xa2, 0xc2, 0x56, 0x3f, 0x4e, 0x0f,
	0xc0, 0x99, 0x61, 0xbb, 0xb5, 0xd3, 0x53, 0x18, 0xcd, 0x50, 0x6d, 0xc0, 0x34, 0x6d, 0x60, 0x1a,
	0x1d, 0x39, 0xec, 0x2c, 0xff, 0xc2, 0x45, 0x16, 0xaa, 0x84, 0xe7, 0x15, 0xc2, 0x5f, 0x5d, 0x18,
	0x35, 0xa2, 0xff, 0x9d, 0xe9, 0xa7, 0xb0, 0x1d, 0xf1, 0x3c, 0xc7, 0x48, 0xe1, 0x92, 0xea, 0xdb,
	0x00, 0xd9, 0x83, 0xa1, 0x5a, 0xe4, 0x39, 0xa6, 0xd2, 0xb3, 0xa7, 0xd6, 0xfe, 0xe8, 0xc8, 0x65,
	0xe7, 0xc6, 0xff, 0x54, 0x18, 0xcc, 0xcb, 0x2c, 0x15, 0xe0, 0x34, 0x13, 0x64, 0x17, 0x6c, 0x29,
	0xa2, 0x8b, 0xa4, 0xa8, 0x40, 0x0f, 0xa4, 0x88, 0xce, 0x0a, 0xf2, 0x04, 0xb6, 0x74, 0xb8, 0xa1,
	0xac, 0xa1, 0x14, 0xd1, 0x5c, 0x83, 0xdc, 0x05, 0x3b, 0x96, 0x4a, 0x77, 0x94, 0xd2, 0x1a, 0xc4,
	0x52, 0x95, 0x1d, 0x3a, 0x6c, 0x3a, 0xfa, 0x65, 0x47, 0x2c, 0x95, 0xee, 0xa0, 0x63, 0x70, 0x4e,
	0xd2, 0xb4, 0x66, 0x87, 0xbe, 0x81, 0xd1, 0x49, 0x9a, 0xb6, 0x7e, 0x15, 0x56, 0xfd, 0x2a, 0x5e,
	0xc2, 0xf8, 0x63, 0x22, 0x95, 0xbc, 0x8f, 0x68, 0x6b, 0x85, 0xe8, 0x19, 0xb8, 0xa6, 0xba, 0x35,
	0xd5, 0xd6, 0x3d, 0x54, 0x7f, 0x86, 0x49, 0xb9, 0x33, 0xd9, 0x4e, 0x0a, 0x0d, 0x32, 0x7a, 0x0f,
	0x91, 0x71, 0xf4, 0xa7, 0x07, 0x76, 0x60, 0xee, 0x25, 0x79, 0x05, 0xc3, 0xea, 0xdc, 0x91, 0x47,
	0xec, 0xee, 0xe1, 0xf3, 0x77, 0xd8, 0xea, 0x19, 0xa5, 0x1d, 0xb2, 0x07, 0xd6, 0x7c, 0xa1, 0x88,
	0xcb, 0x9a, 0xf7, 0x66, 0x7d, 0x61, 0x5f, 0x8b, 0x90, 0x8c, 0xd9, 0x8a, 0x98, 0x7d, 0x97, 0x35,
	0xb5, 0x49, 0x3b, 0xe4, 0x10, 0xec, 0x52, 0x73, 0x64, 0xc2, 0xee, 0x88, 0x6f, 0xdd, 0x77, 0x5f,
	0x80, 0x35, 0x43, 0x0d, 0xa0, 0xa9, 0x3c, 0xdf, 0x61, 0x0d, 0x71, 0x95, 0x55, 0x27, 0x69, 0x4a,
	0x5c, 0xd6, 0x7c, 0x01, 0xbe, 0xc3, 0x1a, 0x0f, 0x80, 0x76, 0xc8, 0x01, 0x0c, 0x0c, 0x55, 0x64,
	0x87, 0xad, 0x12, 0xec, 0x8f, 0xd9, 0x0a, 0x87, 0xb4, 0x63, 0x36, 0x55, 0xee, 0x4f, 0x6f, 0xea,
	0x0e, 0x2f, 0x6b, 0x80, 0x5e, 0xda, 0xe6, 0xbf, 0xe8, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x31, 0x02, 0xbd, 0xa6, 0x9b, 0x06, 0x00, 0x00,
}
