// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package ssh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParameter) Reset()         { *m = NoParameter{} }
func (m *NoParameter) String() string { return proto.CompactTextString(m) }
func (*NoParameter) ProtoMessage()    {}
func (*NoParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *NoParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParameter.Unmarshal(m, b)
}
func (m *NoParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParameter.Marshal(b, m, deterministic)
}
func (m *NoParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParameter.Merge(m, src)
}
func (m *NoParameter) XXX_Size() int {
	return xxx_messageInfo_NoParameter.Size(m)
}
func (m *NoParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParameter.DiscardUnknown(m)
}

var xxx_messageInfo_NoParameter proto.InternalMessageInfo

type Response struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TestingParameter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey           string   `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,6,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestingParameter) Reset()         { *m = TestingParameter{} }
func (m *TestingParameter) String() string { return proto.CompactTextString(m) }
func (*TestingParameter) ProtoMessage()    {}
func (*TestingParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *TestingParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestingParameter.Unmarshal(m, b)
}
func (m *TestingParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestingParameter.Marshal(b, m, deterministic)
}
func (m *TestingParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestingParameter.Merge(m, src)
}
func (m *TestingParameter) XXX_Size() int {
	return xxx_messageInfo_TestingParameter.Size(m)
}
func (m *TestingParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_TestingParameter.DiscardUnknown(m)
}

var xxx_messageInfo_TestingParameter proto.InternalMessageInfo

func (m *TestingParameter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TestingParameter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *TestingParameter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TestingParameter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TestingParameter) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *TestingParameter) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type PutParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey           string   `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,7,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutParameter) Reset()         { *m = PutParameter{} }
func (m *PutParameter) String() string { return proto.CompactTextString(m) }
func (*PutParameter) ProtoMessage()    {}
func (*PutParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *PutParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutParameter.Unmarshal(m, b)
}
func (m *PutParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutParameter.Marshal(b, m, deterministic)
}
func (m *PutParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutParameter.Merge(m, src)
}
func (m *PutParameter) XXX_Size() int {
	return xxx_messageInfo_PutParameter.Size(m)
}
func (m *PutParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_PutParameter.DiscardUnknown(m)
}

var xxx_messageInfo_PutParameter proto.InternalMessageInfo

func (m *PutParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PutParameter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PutParameter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PutParameter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PutParameter) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PutParameter) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *PutParameter) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type ExecParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Bash                 string   `protobuf:"bytes,2,opt,name=bash,proto3" json:"bash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecParameter) Reset()         { *m = ExecParameter{} }
func (m *ExecParameter) String() string { return proto.CompactTextString(m) }
func (*ExecParameter) ProtoMessage()    {}
func (*ExecParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *ExecParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecParameter.Unmarshal(m, b)
}
func (m *ExecParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecParameter.Marshal(b, m, deterministic)
}
func (m *ExecParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecParameter.Merge(m, src)
}
func (m *ExecParameter) XXX_Size() int {
	return xxx_messageInfo_ExecParameter.Size(m)
}
func (m *ExecParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecParameter.DiscardUnknown(m)
}

var xxx_messageInfo_ExecParameter proto.InternalMessageInfo

func (m *ExecParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ExecParameter) GetBash() string {
	if m != nil {
		return m.Bash
	}
	return ""
}

type ExecResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{5}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *ExecResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ExecResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DeleteParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParameter) Reset()         { *m = DeleteParameter{} }
func (m *DeleteParameter) String() string { return proto.CompactTextString(m) }
func (*DeleteParameter) ProtoMessage()    {}
func (*DeleteParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{6}
}

func (m *DeleteParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParameter.Unmarshal(m, b)
}
func (m *DeleteParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParameter.Marshal(b, m, deterministic)
}
func (m *DeleteParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParameter.Merge(m, src)
}
func (m *DeleteParameter) XXX_Size() int {
	return xxx_messageInfo_DeleteParameter.Size(m)
}
func (m *DeleteParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParameter.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParameter proto.InternalMessageInfo

func (m *DeleteParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type GetParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParameter) Reset()         { *m = GetParameter{} }
func (m *GetParameter) String() string { return proto.CompactTextString(m) }
func (*GetParameter) ProtoMessage()    {}
func (*GetParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7}
}

func (m *GetParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParameter.Unmarshal(m, b)
}
func (m *GetParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParameter.Marshal(b, m, deterministic)
}
func (m *GetParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParameter.Merge(m, src)
}
func (m *GetParameter) XXX_Size() int {
	return xxx_messageInfo_GetParameter.Size(m)
}
func (m *GetParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GetParameter proto.InternalMessageInfo

func (m *GetParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type GetResponse struct {
	Error                uint32       `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Information `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{8}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *GetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetResponse) GetData() *Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type Information struct {
	Identity             string          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Host                 string          `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32          `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username             string          `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Connected            string          `protobuf:"bytes,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Tunnels              []*TunnelOption `protobuf:"bytes,6,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Information) Reset()         { *m = Information{} }
func (m *Information) String() string { return proto.CompactTextString(m) }
func (*Information) ProtoMessage()    {}
func (*Information) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{9}
}

func (m *Information) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information.Unmarshal(m, b)
}
func (m *Information) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information.Marshal(b, m, deterministic)
}
func (m *Information) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information.Merge(m, src)
}
func (m *Information) XXX_Size() int {
	return xxx_messageInfo_Information.Size(m)
}
func (m *Information) XXX_DiscardUnknown() {
	xxx_messageInfo_Information.DiscardUnknown(m)
}

var xxx_messageInfo_Information proto.InternalMessageInfo

func (m *Information) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Information) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Information) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Information) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Information) GetConnected() string {
	if m != nil {
		return m.Connected
	}
	return ""
}

func (m *Information) GetTunnels() []*TunnelOption {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

type TunnelOption struct {
	SrcIp                string   `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort              uint32   `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp                string   `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort              uint32   `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelOption) Reset()         { *m = TunnelOption{} }
func (m *TunnelOption) String() string { return proto.CompactTextString(m) }
func (*TunnelOption) ProtoMessage()    {}
func (*TunnelOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{10}
}

func (m *TunnelOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelOption.Unmarshal(m, b)
}
func (m *TunnelOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelOption.Marshal(b, m, deterministic)
}
func (m *TunnelOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelOption.Merge(m, src)
}
func (m *TunnelOption) XXX_Size() int {
	return xxx_messageInfo_TunnelOption.Size(m)
}
func (m *TunnelOption) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelOption.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelOption proto.InternalMessageInfo

func (m *TunnelOption) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *TunnelOption) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *TunnelOption) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *TunnelOption) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

type AllResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllResponse) Reset()         { *m = AllResponse{} }
func (m *AllResponse) String() string { return proto.CompactTextString(m) }
func (*AllResponse) ProtoMessage()    {}
func (*AllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{11}
}

func (m *AllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllResponse.Unmarshal(m, b)
}
func (m *AllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllResponse.Marshal(b, m, deterministic)
}
func (m *AllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllResponse.Merge(m, src)
}
func (m *AllResponse) XXX_Size() int {
	return xxx_messageInfo_AllResponse.Size(m)
}
func (m *AllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllResponse proto.InternalMessageInfo

func (m *AllResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *AllResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AllResponse) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListsParameter struct {
	Identity             []string `protobuf:"bytes,1,rep,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListsParameter) Reset()         { *m = ListsParameter{} }
func (m *ListsParameter) String() string { return proto.CompactTextString(m) }
func (*ListsParameter) ProtoMessage()    {}
func (*ListsParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{12}
}

func (m *ListsParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsParameter.Unmarshal(m, b)
}
func (m *ListsParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsParameter.Marshal(b, m, deterministic)
}
func (m *ListsParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsParameter.Merge(m, src)
}
func (m *ListsParameter) XXX_Size() int {
	return xxx_messageInfo_ListsParameter.Size(m)
}
func (m *ListsParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsParameter.DiscardUnknown(m)
}

var xxx_messageInfo_ListsParameter proto.InternalMessageInfo

func (m *ListsParameter) GetIdentity() []string {
	if m != nil {
		return m.Identity
	}
	return nil
}

type ListsResponse struct {
	Error                uint32         `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Information `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListsResponse) Reset()         { *m = ListsResponse{} }
func (m *ListsResponse) String() string { return proto.CompactTextString(m) }
func (*ListsResponse) ProtoMessage()    {}
func (*ListsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{13}
}

func (m *ListsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsResponse.Unmarshal(m, b)
}
func (m *ListsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsResponse.Marshal(b, m, deterministic)
}
func (m *ListsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsResponse.Merge(m, src)
}
func (m *ListsResponse) XXX_Size() int {
	return xxx_messageInfo_ListsResponse.Size(m)
}
func (m *ListsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListsResponse proto.InternalMessageInfo

func (m *ListsResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *ListsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListsResponse) GetData() []*Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type TunnelsParameter struct {
	Identity             string          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Tunnels              []*TunnelOption `protobuf:"bytes,2,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TunnelsParameter) Reset()         { *m = TunnelsParameter{} }
func (m *TunnelsParameter) String() string { return proto.CompactTextString(m) }
func (*TunnelsParameter) ProtoMessage()    {}
func (*TunnelsParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{14}
}

func (m *TunnelsParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelsParameter.Unmarshal(m, b)
}
func (m *TunnelsParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelsParameter.Marshal(b, m, deterministic)
}
func (m *TunnelsParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelsParameter.Merge(m, src)
}
func (m *TunnelsParameter) XXX_Size() int {
	return xxx_messageInfo_TunnelsParameter.Size(m)
}
func (m *TunnelsParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelsParameter.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelsParameter proto.InternalMessageInfo

func (m *TunnelsParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *TunnelsParameter) GetTunnels() []*TunnelOption {
	if m != nil {
		return m.Tunnels
	}
	return nil
}

type FreePortResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 uint32   `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreePortResponse) Reset()         { *m = FreePortResponse{} }
func (m *FreePortResponse) String() string { return proto.CompactTextString(m) }
func (*FreePortResponse) ProtoMessage()    {}
func (*FreePortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{15}
}

func (m *FreePortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreePortResponse.Unmarshal(m, b)
}
func (m *FreePortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreePortResponse.Marshal(b, m, deterministic)
}
func (m *FreePortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreePortResponse.Merge(m, src)
}
func (m *FreePortResponse) XXX_Size() int {
	return xxx_messageInfo_FreePortResponse.Size(m)
}
func (m *FreePortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FreePortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FreePortResponse proto.InternalMessageInfo

func (m *FreePortResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *FreePortResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FreePortResponse) GetData() uint32 {
	if m != nil {
		return m.Data
	}
	return 0
}

func init() {
	proto.RegisterType((*NoParameter)(nil), "ssh.NoParameter")
	proto.RegisterType((*Response)(nil), "ssh.Response")
	proto.RegisterType((*TestingParameter)(nil), "ssh.TestingParameter")
	proto.RegisterType((*PutParameter)(nil), "ssh.PutParameter")
	proto.RegisterType((*ExecParameter)(nil), "ssh.ExecParameter")
	proto.RegisterType((*ExecResponse)(nil), "ssh.ExecResponse")
	proto.RegisterType((*DeleteParameter)(nil), "ssh.DeleteParameter")
	proto.RegisterType((*GetParameter)(nil), "ssh.GetParameter")
	proto.RegisterType((*GetResponse)(nil), "ssh.GetResponse")
	proto.RegisterType((*Information)(nil), "ssh.Information")
	proto.RegisterType((*TunnelOption)(nil), "ssh.TunnelOption")
	proto.RegisterType((*AllResponse)(nil), "ssh.AllResponse")
	proto.RegisterType((*ListsParameter)(nil), "ssh.ListsParameter")
	proto.RegisterType((*ListsResponse)(nil), "ssh.ListsResponse")
	proto.RegisterType((*TunnelsParameter)(nil), "ssh.TunnelsParameter")
	proto.RegisterType((*FreePortResponse)(nil), "ssh.FreePortResponse")
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc) }

var fileDescriptor_367072455c71aedc = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x6d, 0xba, 0x89, 0x93, 0x8e, 0xe3, 0xdf, 0x2f, 0x5d, 0x5a, 0xc9, 0x44, 0x08, 0xaa, 0x15,
	0x87, 0x42, 0x4b, 0x11, 0x41, 0x9c, 0x51, 0x25, 0xa0, 0x2a, 0xa0, 0x12, 0x45, 0xbd, 0x55, 0xa8,
	0x72, 0x93, 0xa1, 0xb1, 0x48, 0xbc, 0xd6, 0xce, 0x06, 0xe8, 0xe7, 0xe2, 0xc2, 0x95, 0x33, 0x5f,
	0x0a, 0xed, 0xae, 0xed, 0x3a, 0x49, 0xff, 0xa4, 0x8a, 0xb8, 0xed, 0xbe, 0x99, 0x59, 0xbf, 0xb7,
	0xf3, 0x76, 0x0c, 0x4d, 0x25, 0x27, 0x1a, 0xd5, 0x5e, 0xaa, 0xa4, 0x96, 0x9c, 0x11, 0x0d, 0x45,
	0x00, 0xfe, 0x91, 0xec, 0x46, 0x2a, 0x1a, 0xa3, 0x46, 0x25, 0x3a, 0xd0, 0xe8, 0x21, 0xa5, 0x32,
	0x21, 0xe4, 0x1b, 0x50, 0x43, 0xa5, 0xa4, 0x0a, 0x2b, 0x5b, 0x95, 0xed, 0xa0, 0xe7, 0x36, 0xbc,
	0x05, 0x6c, 0x4c, 0xe7, 0xe1, 0xea, 0x56, 0x65, 0x7b, 0xad, 0x67, 0x96, 0xe2, 0x67, 0x05, 0x5a,
	0xc7, 0x48, 0x3a, 0x4e, 0xce, 0x8b, 0x83, 0x38, 0x87, 0xea, 0x50, 0x92, 0xb6, 0xb5, 0x6b, 0x3d,
	0xbb, 0x36, 0x58, 0x2a, 0x95, 0xb6, 0xb5, 0x41, 0xcf, 0xae, 0x79, 0x1b, 0x1a, 0x13, 0x42, 0x95,
	0x44, 0x63, 0x0c, 0x99, 0xcd, 0x2d, 0xf6, 0x26, 0x96, 0x46, 0x44, 0xdf, 0xa5, 0x1a, 0x84, 0x55,
	0x17, 0xcb, 0xf7, 0xfc, 0x11, 0xf8, 0xa9, 0x8a, 0xbf, 0x45, 0x1a, 0x4f, 0xbf, 0xe2, 0x45, 0x58,
	0xb3, 0x61, 0xc8, 0xa0, 0x0f, 0x78, 0xc1, 0x1f, 0x02, 0x98, 0xe4, 0x74, 0xa8, 0x22, 0xc2, 0xd0,
	0xcb, 0xe2, 0x05, 0x22, 0xfe, 0x54, 0xa0, 0xd9, 0x9d, 0xe8, 0x4b, 0xc6, 0x6d, 0x68, 0xc4, 0x03,
	0x4c, 0x74, 0xac, 0x2f, 0x32, 0xd6, 0xc5, 0xbe, 0x50, 0xb3, 0x7a, 0x85, 0x1a, 0x76, 0x8d, 0x9a,
	0xea, 0x0d, 0x6a, 0x6a, 0x37, 0xab, 0xf1, 0x6e, 0x51, 0x53, 0x9f, 0x53, 0xf3, 0x1a, 0x82, 0xb7,
	0x3f, 0xb0, 0xbf, 0xb0, 0x9a, 0xb3, 0x88, 0x86, 0xb9, 0x1a, 0xb3, 0x16, 0xef, 0xa1, 0x69, 0x0e,
	0xb8, 0x6b, 0xf3, 0xcd, 0x59, 0x83, 0x48, 0x47, 0x59, 0xef, 0xec, 0x5a, 0x3c, 0x83, 0xff, 0xdf,
	0xe0, 0x08, 0x35, 0x2e, 0x44, 0x47, 0x3c, 0x85, 0xe6, 0x01, 0x2e, 0xd6, 0x08, 0x71, 0x02, 0xfe,
	0x01, 0xea, 0x3b, 0xb3, 0x7c, 0x5c, 0x62, 0xe9, 0x77, 0x5a, 0x7b, 0x44, 0xc3, 0xbd, 0xc3, 0xe4,
	0x8b, 0x54, 0xe3, 0x48, 0xc7, 0x32, 0xc9, 0x78, 0xff, 0xaa, 0x80, 0x5f, 0x42, 0xff, 0xb9, 0x23,
	0x1e, 0xc0, 0x5a, 0x5f, 0x26, 0x09, 0xf6, 0x35, 0xe6, 0x96, 0xb8, 0x04, 0xf8, 0x0e, 0xd4, 0xf5,
	0x24, 0x49, 0x70, 0x44, 0xa1, 0xb7, 0xc5, 0xb6, 0xfd, 0xce, 0xba, 0xa5, 0x7d, 0x6c, 0xb1, 0x4f,
	0xa9, 0xe5, 0x9d, 0x67, 0x08, 0x05, 0xcd, 0x72, 0x80, 0x6f, 0x82, 0x47, 0xaa, 0x7f, 0x1a, 0xa7,
	0x19, 0xf1, 0x1a, 0xa9, 0xfe, 0x61, 0xca, 0xef, 0x43, 0xc3, 0xc0, 0xa5, 0x57, 0x58, 0x27, 0xd5,
	0xef, 0x1a, 0xa2, 0x9b, 0xe0, 0x0d, 0x48, 0x9b, 0x0a, 0xd7, 0xca, 0xda, 0x80, 0xb4, 0xab, 0x30,
	0xb0, 0xad, 0xa8, 0xba, 0x8a, 0x01, 0x69, 0x53, 0x21, 0x0e, 0xc1, 0xdf, 0x1f, 0x8d, 0x96, 0x70,
	0x0c, 0x2b, 0x1c, 0xb3, 0x0b, 0xff, 0x7d, 0x8c, 0x49, 0xd3, 0x75, 0x26, 0x60, 0x53, 0x26, 0xf8,
	0x0c, 0x81, 0xcd, 0x5e, 0xc2, 0x06, 0xec, 0x06, 0x1b, 0x9c, 0x40, 0xcb, 0xdd, 0x25, 0x2d, 0xf6,
	0x9c, 0x4a, 0x8d, 0x5a, 0xbd, 0xb5, 0x51, 0x47, 0xd0, 0x7a, 0xa7, 0x10, 0xcd, 0x05, 0x2e, 0xf5,
	0xd6, 0x02, 0x47, 0xb6, 0xf3, 0x9b, 0x81, 0xd7, 0xb3, 0x53, 0x9d, 0xbf, 0x80, 0x7a, 0x36, 0x86,
	0xf9, 0xa6, 0x63, 0x30, 0x33, 0x94, 0xdb, 0x81, 0x85, 0xf3, 0xef, 0x8a, 0x15, 0xfe, 0x04, 0x58,
	0x77, 0xa2, 0xb9, 0x23, 0x5c, 0x9e, 0x86, 0xf3, 0xa9, 0xcf, 0xa1, 0x6a, 0x06, 0x04, 0xe7, 0x36,
	0x30, 0x35, 0x6c, 0xda, 0xeb, 0x05, 0x36, 0x55, 0xe0, 0xb9, 0x29, 0xc0, 0x37, 0x6c, 0x78, 0x66,
	0x24, 0xcc, 0x7f, 0x61, 0x17, 0xd8, 0x01, 0xe6, 0x64, 0xca, 0x13, 0xa1, 0xdd, 0xca, 0xa1, 0x52,
	0xf6, 0x0e, 0xb0, 0xfd, 0xd1, 0x88, 0xbb, 0x50, 0xe9, 0x17, 0x96, 0x25, 0x97, 0x9c, 0x29, 0x56,
	0x78, 0x07, 0x6a, 0xd6, 0x31, 0xfc, 0x9e, 0x0d, 0x4e, 0x7b, 0xad, 0xcd, 0x2f, 0xc1, 0x52, 0x8d,
	0xb9, 0x4e, 0xd7, 0xb4, 0xfc, 0x3a, 0x67, 0x4c, 0x31, 0xaf, 0xe0, 0x15, 0x34, 0xf2, 0xe6, 0x5e,
	0x41, 0xcc, 0x9d, 0x32, 0xdb, 0x7d, 0xb1, 0x72, 0xe6, 0xd9, 0xff, 0xf1, 0xcb, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x22, 0xa4, 0xc5, 0x9f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	Testing(ctx context.Context, in *TestingParameter, opts ...grpc.CallOption) (*Response, error)
	Put(ctx context.Context, in *PutParameter, opts ...grpc.CallOption) (*Response, error)
	Exec(ctx context.Context, in *ExecParameter, opts ...grpc.CallOption) (*ExecResponse, error)
	Delete(ctx context.Context, in *DeleteParameter, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *GetParameter, opts ...grpc.CallOption) (*GetResponse, error)
	All(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*AllResponse, error)
	Lists(ctx context.Context, in *ListsParameter, opts ...grpc.CallOption) (*ListsResponse, error)
	Tunnels(ctx context.Context, in *TunnelsParameter, opts ...grpc.CallOption) (*Response, error)
	FreePort(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*FreePortResponse, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Testing(ctx context.Context, in *TestingParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ssh.Router/Testing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Put(ctx context.Context, in *PutParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ssh.Router/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Exec(ctx context.Context, in *ExecParameter, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/ssh.Router/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Delete(ctx context.Context, in *DeleteParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ssh.Router/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Get(ctx context.Context, in *GetParameter, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/ssh.Router/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) All(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := c.cc.Invoke(ctx, "/ssh.Router/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Lists(ctx context.Context, in *ListsParameter, opts ...grpc.CallOption) (*ListsResponse, error) {
	out := new(ListsResponse)
	err := c.cc.Invoke(ctx, "/ssh.Router/Lists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Tunnels(ctx context.Context, in *TunnelsParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ssh.Router/Tunnels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) FreePort(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*FreePortResponse, error) {
	out := new(FreePortResponse)
	err := c.cc.Invoke(ctx, "/ssh.Router/FreePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	Testing(context.Context, *TestingParameter) (*Response, error)
	Put(context.Context, *PutParameter) (*Response, error)
	Exec(context.Context, *ExecParameter) (*ExecResponse, error)
	Delete(context.Context, *DeleteParameter) (*Response, error)
	Get(context.Context, *GetParameter) (*GetResponse, error)
	All(context.Context, *NoParameter) (*AllResponse, error)
	Lists(context.Context, *ListsParameter) (*ListsResponse, error)
	Tunnels(context.Context, *TunnelsParameter) (*Response, error)
	FreePort(context.Context, *NoParameter) (*FreePortResponse, error)
}

// UnimplementedRouterServer can be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (*UnimplementedRouterServer) Testing(ctx context.Context, req *TestingParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Testing not implemented")
}
func (*UnimplementedRouterServer) Put(ctx context.Context, req *PutParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedRouterServer) Exec(ctx context.Context, req *ExecParameter) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (*UnimplementedRouterServer) Delete(ctx context.Context, req *DeleteParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedRouterServer) Get(ctx context.Context, req *GetParameter) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRouterServer) All(ctx context.Context, req *NoParameter) (*AllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedRouterServer) Lists(ctx context.Context, req *ListsParameter) (*ListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lists not implemented")
}
func (*UnimplementedRouterServer) Tunnels(ctx context.Context, req *TunnelsParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tunnels not implemented")
}
func (*UnimplementedRouterServer) FreePort(ctx context.Context, req *NoParameter) (*FreePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreePort not implemented")
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_Testing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestingParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Testing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Testing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Testing(ctx, req.(*TestingParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Put(ctx, req.(*PutParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Exec(ctx, req.(*ExecParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Delete(ctx, req.(*DeleteParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Get(ctx, req.(*GetParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).All(ctx, req.(*NoParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Lists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListsParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Lists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Lists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Lists(ctx, req.(*ListsParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Tunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelsParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Tunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/Tunnels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Tunnels(ctx, req.(*TunnelsParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_FreePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).FreePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssh.Router/FreePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).FreePort(ctx, req.(*NoParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssh.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Testing",
			Handler:    _Router_Testing_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Router_Put_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Router_Exec_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Router_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Router_Get_Handler,
		},
		{
			MethodName: "All",
			Handler:    _Router_All_Handler,
		},
		{
			MethodName: "Lists",
			Handler:    _Router_Lists_Handler,
		},
		{
			MethodName: "Tunnels",
			Handler:    _Router_Tunnels_Handler,
		},
		{
			MethodName: "FreePort",
			Handler:    _Router_FreePort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
